name: Parent Sync

on:
  push:
    branches: 
      - staging

jobs:
  parent-sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with: 
          repository: orbital-skylab/skylab-e2e
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true

      - name: Pull & update submodules recursively
        run: |
          git submodule update --remote

      - name: Commit
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions - update submodules"
          git add --all
          git commit -m "ci: update submodules" || echo "No changes to commit"
          git push